export type PartnerEcosystemItem = {
  id: string;
  name: string;
  shortName: string;
  logoPath: string;
  logoTheme?: "light" | "dark";
  focus: string;
  description: string;
  areas: readonly string[];
};

export const partnerEcosystem: readonly PartnerEcosystemItem[] = [
  {
    id: "link Plus",
    name: "Link Plus",
    shortName: "Link Plus",
    logoPath: "/partners/linkplus.svg",
    focus: "Digital transformation and enterprise technology enablement",
    description:
      "Connected technology solutions and delivery support that help organizations modernize operations with confidence.",
    areas: ["Digital services", "Enterprise connectivity", "Transformation", "Innovation"],
  },
  {
    id: "microsoft",
    name: "Microsoft",
    shortName: "Microsoft",
    logoPath: "/microsoft.png",
    focus: "Cloud, data and modern workplace technology",
    description:
      "Practical Microsoft platform guidance and implementation support for organizations modernizing the way they operate.",
    areas: ["Microsoft Azure", "Modern Workplace", "Data & AI", "Security"],
  },
  {
    id: "cisco",
    name: "Cisco",
    shortName: "Cisco",
    logoPath: "/partners/cisco.svg",
    focus: "Secure, connected operations",
    description:
      "Network and collaboration capabilities that keep distributed teams, locations, and services reliably connected.",
    areas: ["Network design", "Secure access", "Collaboration", "Observability"],
  },
  {
    id: "dell",
    name: "Dell Technologies",
    shortName: "Dell",
    logoPath: "/partners/dell.svg",
    focus: "Business-critical infrastructure",
    description:
      "Infrastructure solutions that support dependable performance, continuity, and scalable operations.",
    areas: ["Compute", "Storage", "Datacentre", "Continuity"],
  },
  {
    id: "vmware",
    name: "VMware",
    shortName: "VMware",
    logoPath: "/partners/vmware.svg",
    focus: "Flexible hybrid cloud foundations",
    description:
      "Virtualization and cloud-management expertise for more resilient, adaptable technology estates.",
    areas: ["Virtualization", "Hybrid cloud", "Automation", "Resilience"],
  },
  {
    id: "fortinet",
    name: "Fortinet",
    shortName: "Fortinet",
    logoPath: "/partners/Fortinet.png",
    focus: "Integrated cyber security",
    description:
      "Security capabilities designed to protect networks, users, applications, and cloud environments together.",
    areas: ["Network security", "Secure access", "Cloud security", "Threat response"],
  },
  {
    id: "crowdstrike",
    name: "CrowdStrike",
    shortName: "CrowdStrike",
    logoPath: "/partners/crowd strike.png",
    focus: "Endpoint protection and threat intelligence",
    description:
      "Modern endpoint and workload protection that helps organizations detect, investigate, and respond with confidence.",
    areas: ["Endpoint security", "Threat intelligence", "Incident response", "Cloud protection"],
  },
  {
    id: "trend-micro",
    name: "Trend Micro",
    shortName: "Trend Micro",
    logoPath: "/partners/trend.png",
    focus: "Resilient cloud and enterprise security",
    description:
      "Layered security expertise for protecting enterprise systems and critical cloud workloads.",
    areas: ["Cloud security", "Workload protection", "Risk visibility", "Compliance"],
  },
  {
    id: "veeam",
    name: "Veeam",
    shortName: "Veeam",
    logoPath: "/partners/veeam.png",
    logoTheme: "dark",
    focus: "Data protection and recovery",
    description:
      "Backup and recovery solutions that help organizations keep business-critical information available.",
    areas: ["Backup", "Disaster recovery", "Data resilience", "Monitoring"],
  },
  {
    id: "zoho",
    name: "Zoho",
    shortName: "Zoho",
    logoPath: "/partners/zoho.png",
    focus: "Connected business applications",
    description:
      "Business applications that help teams coordinate work, improve service delivery, and automate everyday operations.",
    areas: ["Business systems", "Automation", "Customer operations", "Collaboration"],
  },
  {
    id: "odoo",
    name: "Odoo",
    shortName: "Odoo",
    logoPath: "/partners/odoo.png",
    focus: "Adaptable business operations",
    description:
      "Integrated business applications that bring finance, operations, sales, and inventory into one adaptable platform.",
    areas: ["ERP", "Operations", "Sales", "Integration"],
  },
  {
    id: "samsung",
    name: "Samsung",
    shortName: "Samsung",
    logoPath: "/partners/samsung.png",
    focus: "Enterprise mobility and display solutions",
    description:
      "Connected device and display experiences that support modern, productive workplaces.",
    areas: ["Mobility", "Displays", "Device management", "Workplace"],
  },
  {
    id: "logitech",
    name: "Logitech",
    shortName: "Logitech",
    logoPath: "/partners/logitech.png",
    focus: "Better collaboration experiences",
    description:
      "Collaboration technology that helps teams communicate and work together more naturally from anywhere.",
    areas: ["Video collaboration", "Meeting rooms", "Hybrid work", "Productivity"],
  },
  {
    id: "apple",
    name: "Apple",
    shortName: "Apple",
    logoPath: "/partners/iphone.png",
    focus: "Secure, intuitive employee technology",
    description:
      "Premium employee devices and endpoint experiences that support secure, productive work.",
    areas: ["End-user computing", "Mobility", "Endpoint management", "Employee experience"],
  },
  {
    id: "acronis",
    name: "Acronis",
    shortName: "Acronis",
    logoPath: "/partners/acronis.png",
    focus: "Cyber protection and data resilience",
    description: "Integrated protection capabilities for safeguarding business data, applications, and systems.",
    areas: ["Backup", "Cyber protection", "Disaster recovery", "Data resilience"],
  },
  {
    id: "antlabs",
    name: "ANTlabs",
    shortName: "ANTlabs",
    logoPath: "/partners/antlabs.png",
    focus: "Secure network access and hospitality connectivity",
    description: "Network access technology for reliable, managed guest and enterprise connectivity.",
    areas: ["Guest Wi-Fi", "Access management", "Hospitality", "Networking"],
  },
  {
    id: "avaya",
    name: "Avaya",
    shortName: "Avaya",
    logoPath: "/partners/avaya.png",
    focus: "Enterprise communications and customer experience",
    description: "Communication platforms that connect employees, customers, and service teams.",
    areas: ["Unified communications", "Contact centres", "Collaboration", "Customer experience"],
  },
  {
    id: "cetis",
    name: "Cetis",
    shortName: "Cetis",
    logoPath: "/partners/Cetis.png",
    focus: "Hospitality communication solutions",
    description: "Purpose-built communication devices and solutions for hospitality environments.",
    areas: ["Hospitality phones", "Guest rooms", "Communications", "Property technology"],
  },
  {
    id: "eset",
    name: "ESET",
    shortName: "ESET",
    logoPath: "/partners/eset.png",
    focus: "Endpoint and business security",
    description: "Layered security for protecting users, devices, and business operations.",
    areas: ["Endpoint security", "Threat prevention", "Encryption", "Cloud protection"],
  },
  {
    id: "grandstream",
    name: "Grandstream",
    shortName: "Grandstream",
    logoPath: "/partners/grand_strem.png",
    focus: "Unified communications and networking",
    description: "Voice, video, networking, and facility-management technology for connected organizations.",
    areas: ["IP telephony", "Networking", "Video collaboration", "Access control"],
  },
  {
    id: "hikvision",
    name: "Hikvision",
    shortName: "Hikvision",
    logoPath: "/partners/hkvision.jpg",
    focus: "Video security and intelligent sensing",
    description: "Video, access, and sensing solutions that support safer, smarter environments.",
    areas: ["Video security", "Access control", "Analytics", "Smart spaces"],
  },
  {
    id: "hpe",
    name: "HPE",
    shortName: "HPE",
    logoPath: "/partners/hpe.png",
    focus: "Enterprise compute, storage, and edge infrastructure",
    description: "Infrastructure platforms designed for scalable, data-driven enterprise operations.",
    areas: ["Compute", "Storage", "Edge", "Hybrid cloud"],
  },
  {
    id: "huawei",
    name: "Huawei",
    shortName: "Huawei",
    logoPath: "/partners/Huawei.png",
    focus: "Enterprise networking and digital infrastructure",
    description: "Connectivity, cloud, and infrastructure technologies for modern digital operations.",
    areas: ["Networking", "Cloud", "Storage", "Digital infrastructure"],
  },
  {
    id: "infraon",
    name: "Infraon",
    shortName: "Infraon",
    logoPath: "/partners/infraon.png",
    focus: "IT operations and infrastructure management",
    description: "Operations platforms that improve visibility, service performance, and infrastructure control.",
    areas: ["IT operations", "Observability", "Service management", "Automation"],
  },
  {
    id: "interel",
    name: "INTEREL",
    shortName: "INTEREL",
    logoPath: "/partners/interel.jpg",
    focus: "Connected guest-room technology",
    description: "Smart room systems that improve guest experience and property efficiency.",
    areas: ["Guest rooms", "Energy management", "Hospitality", "Smart controls"],
  },
  {
    id: "lg",
    name: "LG",
    shortName: "LG",
    logoPath: "/partners/lg.png",
    focus: "Commercial displays and connected experiences",
    description: "Display and device technology for workplaces, hospitality, and customer environments.",
    areas: ["Commercial displays", "Hospitality TV", "Digital signage", "Devices"],
  },
  {
    id: "mitel",
    name: "Mitel",
    shortName: "Mitel",
    logoPath: "/partners/mitel.png",
    focus: "Business communications and collaboration",
    description: "Communication systems that support connected employees and responsive customer service.",
    areas: ["Unified communications", "Voice", "Contact centres", "Collaboration"],
  },
  {
    id: "morpheus",
    name: "Morpheus",
    shortName: "Morpheus",
    logoPath: "/partners/morpheus.jpg",
    focus: "Hybrid cloud management and automation",
    description: "Cloud-management capabilities for orchestrating infrastructure, applications, and governance.",
    areas: ["Cloud management", "Automation", "Orchestration", "Governance"],
  },
  {
    id: "nutanix",
    name: "Nutanix",
    shortName: "Nutanix",
    logoPath: "/partners/nutanix.png",
    focus: "Hybrid multicloud infrastructure",
    description: "Cloud platforms that simplify infrastructure operations across private and public environments.",
    areas: ["Hyperconverged infrastructure", "Hybrid cloud", "Virtualization", "Automation"],
  },
  {
    id: "palo-alto-networks",
    name: "Palo Alto Networks",
    shortName: "Palo Alto",
    logoPath: "/partners/paloalto.png",
    focus: "Enterprise cyber security",
    description: "Integrated security capabilities for networks, cloud environments, and security operations.",
    areas: ["Network security", "Cloud security", "SOC", "Zero trust"],
  },
  {
    id: "salto",
    name: "SALTO",
    shortName: "SALTO",
    logoPath: "/partners/salto inspired access.jpg",
    focus: "Smart access control",
    description: "Connected access solutions for secure, flexible building and user experiences.",
    areas: ["Access control", "Smart buildings", "Identity", "Security"],
  },
  {
    id: "sangfor",
    name: "Sangfor",
    shortName: "Sangfor",
    logoPath: "/partners/sangfor.png",
    focus: "Cloud infrastructure and cyber security",
    description: "Infrastructure and security solutions built to simplify resilient digital operations.",
    areas: ["Cyber security", "Cloud", "Virtualization", "Secure access"],
  },
  {
    id: "servicefix",
    name: "Servicefix",
    shortName: "Servicefix",
    logoPath: "/partners/servicefix.jpg",
    focus: "Service management and workflow enablement",
    description: "Service-management capabilities that help teams coordinate support and operational workflows.",
    areas: ["Service management", "Workflow", "Support operations", "Automation"],
  },
  {
    id: "sonicwall",
    name: "SonicWall",
    shortName: "SonicWall",
    logoPath: "/partners/sonicwall.jpg",
    focus: "Network and endpoint security",
    description: "Security technology for protecting networks, users, and distributed business environments.",
    areas: ["Firewalls", "Secure access", "Endpoint security", "Threat protection"],
  },
  {
    id: "sophos",
    name: "Sophos",
    shortName: "Sophos",
    logoPath: "/partners/sophos.png",
    focus: "Managed and integrated cyber security",
    description: "Security products and services that protect endpoints, networks, email, and cloud workloads.",
    areas: ["Endpoint security", "Network security", "Managed detection", "Cloud security"],
  },
] as const;
